In [1]:
import pandas as pd

In [165]:
import pandas as pd
dict1 = {'Name': ['Priyang','Aadhya','Krishna', 'Vedant','Parshv','Mittal','Archana'],
         'Marks': [98,44,76,87,64,54,65],
         'Gender':['male','female','female','male','male','female','female']
        }
df1 = pd.DataFrame(dict1)
# df1=pd.read_csv('Ecommerce Purchases')
df1

      Name  Marks  Gender
0  Priyang     98    male
1   Aadhya     44  female
2  Krishna     76  female
3   Vedant     87    male
4   Parshv     64    male
5   Mittal     54  female
6  Archana     65  female

If left empty it will show first 5 elements

In [3]:
df1.head(3)

      Name  Marks  Gender
0  Priyang     98    male
1   Aadhya     44  female
2  Krishna     76  female

If left empty it will show last 5 elements

In [4]:
df1.tail(3)

      Name  Marks  Gender
4   Parshv     64    male
5   Mittal     54  female
6  Archana     65  female

Finding shape (rows,columns) of a dataframe meaning the finding the attribute not function hence no ()

In [5]:
df1.shape

(7, 3)

In [6]:
print("rows: ", df1.shape[0])
print("columns: ",df1.shape[1])

rows:  7
columns:  3

Getting Information about our Dataset like total numbers rows, total number of columns, datatypes of each column and memory requirement

In [7]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      str
dtypes: int64(1), str(2)
memory usage: 300.0 bytes

try axis=1 for row wise null value sum

In [8]:
 df1.isnull().sum(axis=0)

Name      0
Marks     0
Gender    0
dtype: int64

Overall statistics for dataset

with include it will show only integer statistics

In [9]:
df1.describe(include='all')

           Name      Marks  Gender
count         7   7.000000       7
unique        7        NaN       2
top     Priyang        NaN  female
freq          1        NaN       4
mean        NaN  69.714286     NaN
std         NaN  18.714649     NaN
min         NaN  44.000000     NaN
25%         NaN  59.000000     NaN
50%         NaN  65.000000     NaN
75%         NaN  81.500000     NaN
max         NaN  98.000000     NaN

Unique values from gender column

In [10]:
df1['Gender'].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

No.of Unique values in gender column

In [11]:
df1['Gender'].nunique()

2

Count of unique values in gender column (very important)

In [12]:
df1['Gender'].value_counts()

Gender
female    4
male      3
Name: count, dtype: int64

total students with marks btw 70 to 90 using between method

In [13]:
df1[df1['Marks']>=70]

      Name  Marks  Gender
0  Priyang     98    male
2  Krishna     76  female
3   Vedant     87    male

In [14]:
len( df1 [  (df1['Marks']>=70)  &  (df1['Marks']<=90)  ] )

2

In [15]:
sum(df1['Marks'].between(70,90))

2

In [16]:
df1['Marks'].mean()

np.float64(69.71428571428571)

In [17]:
df1['Marks'].min()

np.int64(44)

In [18]:
df1['Marks'].max()

np.int64(98)

Apply Method(creating own user defined functions) and creating your own columns

In [19]:
def marks(x):
    return x//2

In [20]:
df1['Half_Marks'] = df1['Marks'].apply(marks)

In [21]:
df1

      Name  Marks  Gender  Half_Marks
0  Priyang     98    male          49
1   Aadhya     44  female          22
2  Krishna     76  female          38
3   Vedant     87    male          43
4   Parshv     64    male          32
5   Mittal     54  female          27
6  Archana     65  female          32

Lets use apply with lambda function on Marks column using which we will finish above 3 lines at one go

In [22]:
df1['Marks'].apply(lambda x:x/2)

0    49.0
1    22.0
2    38.0
3    43.5
4    32.0
5    27.0
6    32.5
Name: Marks, dtype: float64

finding length of strings using apply

In [23]:
df1['Name'].apply(len)

0    7
1    6
2    7
3    6
4    6
5    6
6    7
Name: Name, dtype: int64

In [167]:
df1['male_female'] = df1['Gender'].map({'male':1,'female':0})
df1

      Name  Marks  Gender  male_female
0  Priyang     98    male            1
1   Aadhya     44  female            0
2  Krishna     76  female            0
3   Vedant     87    male            1
4   Parshv     64    male            1
5   Mittal     54  female            0
6  Archana     65  female            0

Drop Column(s)

In [168]:
df1

      Name  Marks  Gender  male_female
0  Priyang     98    male            1
1   Aadhya     44  female            0
2  Krishna     76  female            0
3   Vedant     87    male            1
4   Parshv     64    male            1
5   Mittal     54  female            0
6  Archana     65  female            0

In [169]:
df1.size

28

In [26]:
df1.drop('male_female',axis = 1)

      Name  Marks  Gender  Half_Marks
0  Priyang     98    male          49
1   Aadhya     44  female          22
2  Krishna     76  female          38
3   Vedant     87    male          43
4   Parshv     64    male          32
5   Mittal     54  female          27
6  Archana     65  female          32

In [27]:
df1.drop(['male_female','Half_Marks'],axis = 1,inplace=True)

In [28]:
df1

      Name  Marks  Gender
0  Priyang     98    male
1   Aadhya     44  female
2  Krishna     76  female
3   Vedant     87    male
4   Parshv     64    male
5   Mittal     54  female
6  Archana     65  female

Print name of columns and row indexes

In [29]:
df1.columns

Index(['Name', 'Marks', 'Gender'], dtype='str')

In [30]:
df1.index

RangeIndex(start=0, stop=7, step=1)

lets perform sorting descending , first as per marks then gender

In [31]:
df1.sort_values(by = ['Marks','Gender'],ascending = False)

      Name  Marks  Gender
0  Priyang     98    male
3   Vedant     87    male
2  Krishna     76  female
6  Archana     65  female
4   Parshv     64    male
5   Mittal     54  female
1   Aadhya     44  female

Display name and marks of female students

In [32]:
df1[df1['Gender']=='female'][['Name','Marks']]

      Name  Marks
1   Aadhya     44
2  Krishna     76
5   Mittal     54
6  Archana     65

Now same using pandas methods

In [33]:
df1[df1['Gender'].isin(['female'])][['Name','Marks']]

      Name  Marks
1   Aadhya     44
2  Krishna     76
5   Mittal     54
6  Archana     65

In [34]:
df1.columns

Index(['Name', 'Marks', 'Gender'], dtype='str')

In [41]:
df1.iat[0,0]

'Priyang'

In [46]:
display(df1[["Marks","Gender"]])

   Marks  Gender
0     98    male
1     44  female
2     76  female
3     87    male
4     64    male
5     54  female
6     65  female

In [159]:
df1[["Marks","Gender"]]

   Marks  Gender
0     98    male
1     44  female
2     76  female
3     87    male
4     64    male
5     54  female
6     65  female

In [160]:
df1

      Name  Marks  Gender
0  Priyang     98    male
1   Aadhya     44  female
2  Krishna     76  female
3   Vedant     87    male
4   Parshv     64    male
5   Mittal     54  female
6  Archana     65  female

In [176]:
df1.loc[2:3][["Marks","Gender"]]

   Marks  Gender
2     76  female
3     87    male